import type { MeetingType } from "../../types/MeetingType";
import type { SpendingType } from "../../types/SpendingType";

export const initialMeetings: MeetingType[] = [
    {
        id: 1,
        person: "Рената",
        date: "2024-10-06T14:00:00Z",
        links: {
            telegram: "https://t.me/RENATAKARAMOVA",
            wfolio: "https://norwayziph.wfolio.pro/disk/06-10-2024-renata-p69x1k",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2000,
    },
    {
        id: 2,
        person: "Алия",
        date: "2024-10-25T13:00:00Z",
        links: {
            telegram: "https://t.me/liyaa_safina",
            wfolio: "https://norwayziph.wfolio.pro/disk/25-10-2024-aliya-k84vj4",
        },
        status: "Сдано",
        location: "Студия",
        amount: 0,
    },
    {
        id: 3,
        person: "Айзиля",
        date: "2024-11-17T17:00:00Z",
        links: {
            telegram: "https://t.me/aizilya_yunusova",
            wfolio: "https://norwayziph.wfolio.pro/disk/17-11-2024-aizcw4zn9",
        },
        status: "Сдано",
        location: "Студия",
        amount: 500,
    },
    {
        id: 4,
        person: "Дарина",
        date: "2024-11-17T17:00:00Z",
        links: {
            telegram: "https://t.me/_darina_talipova",
            wfolio: "https://norwayziph.wfolio.pro/disk/17-11-2024-darina-11gpfg",
        },
        status: "Сдано",
        location: "Студия",
        amount: 0,
    },
    {
        id: 5,
        person: "Эвелина",
        date: "2024-11-23T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://norwayziph.wfolio.pro/disk/24-11-2024-evelina-f5r36g",
        },
        status: "Сдано",
        location: "Студия",
        amount: 0,
    },
    {
        id: 6,
        person: "Аделя",
        date: "2024-11-22T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://norwayziph.wfolio.pro/disk/24-11-2024-adelya-p6vjhm",
        },
        status: "Сдано",
        location: "Студия",
        amount: 0,
    },
    {
        id: 7,
        person: "Эля",
        date: "2024-11-24T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://norwayziph.wfolio.pro/disk/24-11-2024-elya-vkxd44",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2500,
    },
    {
        id: 8,
        person: "Алиса",
        date: "2025-01-17T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://wfolio.ru/my/disk/projects/9547586/folders/15232708",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2500,
    },
    {
        id: 9,
        person: "Виктор",
        date: "2025-01-28T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://wfolio.ru/my/disk/projects/9547586/folders/15232708",
        },
        status: "Сдано",
        location: "Студия",
        amount: 1500,
    },
    {
        id: 10,
        person: "Лиза",
        date: "2025-02-04T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://wfolio.ru/my/disk/projects/9547586/folders/15232708",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2000,
    },
    {
        id: 11,
        person: "Изаура",
        date: "2025-04-19T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://wfolio.ru/my/disk/projects/9547586/folders/15232708",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2000,
    },
    {
        id: 12,
        person: "Настя",
        date: "2025-07-12T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://wfolio.ru/my/disk/projects/9547586/folders/15232708",
        },
        status: "Сдано",
        location: "Студия",
        amount: 1000,
    },
    {
        id: 13,
        person: "Семья крещение",
        date: "2025-07-19T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://wfolio.ru/my/disk/projects/9547586/folders/15232708",
        },
        status: "Сдано",
        location: "Студия",
        amount: 1500,
    },
    {
        id: 14,
        person: "Сертификат",
        date: "2025-06-30T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://wfolio.ru/my/disk/projects/9547586/folders/15232708",
        },
        status: "Сдано",
        location: "Студия",
        amount: 1500,
    },
    {
        id: 15,
        person: "Ангелина LS",
        date: "2025-08-03T17:00:00Z",
        links: {
            telegram: "https://t.me/Angel_isa",
            wfolio: "https://norwayziph.wfolio.pro/disk/03-08-2025-angelina-artyom-3fkj9p",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2000,
    },
    {
        id: 16,
        person: "Рита",
        date: "2025-08-03T17:00:00Z",
        links: {
            telegram: "https://t.me/hgfugv",
            wfolio: "https://norwayziph.wfolio.pro/disk/03-08-2025-angelina-artyom-3fkj9p",
        },
        status: "Сдано",
        location: "Студия",
        amount: 1800,
    },
    {
        id: 17,
        person: "Матвей+Лиза",
        date: "2025-09-19T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://norwayziph.wfolio.pro/disk/19-09-2025-liza-matvey-65mhtq",
        },
        status: "Сдано",
        location: "Студия",
        amount: 5000,
    },
    {
        id: 18,
        person: "Силвия",
        date: "2025-09-20T17:00:00Z",
        links: {
            telegram: "https://t.me/Donevass",
            wfolio: "https://norwayziph.wfolio.pro/disk/20-09-2025-silviya-sq8g1h/tsvet",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2500,
    },
    {
        id: 19,
        person: "др Миланы",
        date: "2025-09-09T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://norwayziph.wfolio.pro/disk/20-09-2025-silviya-sq8g1h/tsvet",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2000,
    },
    {
        id: 20,
        person: "Свадьба Анна",
        date: "2025-09-09T17:00:00Z",
        links: {
            telegram: "https://t.me/ananevanna",
            wfolio: "https://norwayziph.wfolio.pro/disk/20-09-2025-silviya-sq8g1h/tsvet",
        },
        status: "Сдано",
        location: "Студия",
        amount: 16000,
    },
    {
        id: 21,
        person: "Виктория",
        date: "2025-09-28T17:00:00Z",
        links: {
            telegram: "https://t.me/Danata123",
            wfolio: "https://norwayziph.wfolio.pro/disk/20-09-2025-silviya-sq8g1h/tsvet",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2000,
    },
    {
        id: 22,
        person: "Савелий",
        date: "2025-09-29T17:00:00Z",
        links: {
            telegram: "https://t.me/guzinba",
            wfolio: "https://norwayziph.wfolio.pro/disk/20-09-2025-silviya-sq8g1h/tsvet",
        },
        status: "Сдано",
        location: "Студия",
        amount: 2500,
    },
    {
        id: 23,
        person: "Изаура",
        date: "2025-09-30T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://norwayziph.wfolio.pro/disk/20-09-2025-silviya-sq8g1h/tsvet",
        },
        status: "Сдано",
        location: "Студия",
        amount: 1850,
    },
    {
        id: 24,
        person: "Айзиля",
        date: "2025-10-19T17:00:00Z",
        links: {
            telegram: "https://t.me/aizilya_yunusova",
            wfolio: "https://norwayziph.wfolio.pro/disk/20-09-2025-silviya-sq8g1h/tsvet",
        },
        status: "Сдано",
        location: "Студия",
        amount: 3000,
    },
    {
        id: 25,
        person: "Тимур",
        date: "2025-11-01T17:00:00Z",
        links: {
            telegram: "https://t.me/ngnnmrt",
            wfolio: "https://norwayziph.wfolio.pro/disk/20-09-2025-silviya-sq8g1h/tsvet",
        },
        status: "Сдано",
        location: "Студия",
        amount: 7777,
    },
    {
        id: 26,
        person: "Наташа",
        date: "2025-12-05T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://norwayziph.wfolio.pro/disk/natasha-dima-xvnhvf",
        },
        status: "Сдано",
        location: "Студия",
        amount: 3250,
    },
    {
        id: 27,
        person: "Эвелина",
        date: "2025-12-10T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
            wfolio: "https://norwayziph.wfolio.pro/disk/natasha-dima-xvnhvf",
        },
        status: "Сдано",
        location: "Студия",
        amount: 3000,
    },
    {
        id: 28,
        person: "Вадим",
        date: "2026-01-22T17:00:00Z",
        deadlineDate: "2026-01-25T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
        },
        status: "В обработке",
        location: "Студия",
    },
    {
        id: 29,
        person: "Коля",
        date: "2026-01-22T17:00:00Z",
        deadlineDate: "2026-01-22T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
        },
        status: "Ждёт обработки",
        location: "Студия",
    },
    {
        id: 30,
        person: "Женя",
        date: "2026-01-22T17:00:00Z",
        deadlineDate: "2026-01-20T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
        },
        status: "В обработке",
        location: "Студия",
    },
    {
        id: 31,
        person: "Альбина",
        date: "2026-01-10T17:00:00Z",
        links: {
            telegram: "https://t.me/neblessed",
        },
        status: "Назначено",
        location: "Студия",
        comment: "Взять большую сумку",
    },
];

export const initialSpendings: SpendingType[] = [
    {
        id: 1,
        spending: "Расходники",
        date: "2025-01-04T14:30:00Z",
        amount: 15930,
    },
];
